import { head, legend, item, blob, wordmark, chip, HUES, icon, ARROW, SEARCH, PHOTO, illo, ico } from "../lib.mjs";

const btn = (text, v = "primary", extra = "", inner = "") => `<${extra.includes("href") ? "a" : "button"} class="noo-btn noo-btn--${v}${v === "secondary" ? " glass glass-1" : ""}${extra.includes("sm") ? " noo-btn--sm" : ""}"${extra.includes("disabled") ? " disabled" : ""}${extra.includes("href") ? ' href="#"' : ' type="button"'}${extra.includes("focus") ? ' style="outline:2px solid var(--accent-deep);outline-offset:2px"' : ""}>${inner}<span class="noo-btn__text">${text}</span></${extra.includes("href") ? "a" : "button"}>`;

const toggle = (on, disabled = false) => `<button type="button" role="switch" aria-checked="${on}" class="noo-toggle"${disabled ? " disabled" : ""}><span class="noo-toggle__knob" aria-hidden="true"></span></button>`;

export const items = [
  item({ name: "Ground", layer: "atom · .noo-ground", desc: "The surface everything sits on: warm grey with 160px grid lines. Glass refracts it; the blob sits on its origin crosshair. Not a background image — a class any element can wear.", reads: "--ground · --grid-box · --grid-line · --grid-line-w", verdict: "Keep",
    note: "Merge <code>.noo-graph</code> into it (Tokens board). Then export it as a component, <code>Ground</code>, so an app never writes the class by hand — both existing apps do.",
    demo: `<div class="rv-row" style="gap:20px;align-items:flex-start"><div class="noo-ground" style="position:relative;width:480px;height:224px;border:1px solid var(--rule);border-radius:var(--r-md);background-position:80px 32px"><span style="position:absolute;left:240px;top:64px;transform:translate(-50%,-50%)">${blob({ size: "md", host: true })}</span></div><p class="rv-cap" style="max-width:26ch">the host blob on a crossing — the one place the refraction has both axes to bend</p></div>` }),
  item({ name: "Blob", layer: "atom · the mark", desc: "A 96 × 64 pill with two eyes, scaled and never redrawn. Tinted glass for a character, clear glass for the host, an outline for the logotype. Blink, look, breathe are plain DOM behaviour.", reads: "--{hue}-tint · --glass-blob-opacity · --eye · --shade · --grid-line", verdict: "Keep",
    note: "The mark is decided and built. Two open items stay open: the dark-theme tints read as flat paint (§13), and the refraction pattern only appears where a grid line crosses the pill. Reads the hue slot once it exists.",
    demo: `<div class="rv-col" style="gap:24px"><div class="rv-row" style="gap:20px;align-items:flex-end">${["nav","sm","md","lg"].map((s) => `<div class="rv-col" style="align-items:center;gap:8px">${blob({ size: s, hue: "peach" })}<span class="rv-cap">${s}</span></div>`).join("")}<div class="rv-col" style="align-items:center;gap:8px">${blob({ size: "md", host: true })}<span class="rv-cap">host · glass</span></div><div class="rv-col" style="align-items:center;gap:8px">${blob({ size: "md", hue: "lavender", sleep: true })}<span class="rv-cap">sleep</span></div><div class="rv-col" style="align-items:center;gap:8px">${blob({ size: "md", logotype: true })}<span class="rv-cap">logotype</span></div></div><div class="rv-row" style="gap:14px">${HUES.filter((h) => h !== "grey").map((h) => blob({ size: "sm", hue: h })).join("")}${blob({ size: "sm", host: true })}</div></div>` }),
  item({ name: "Wordmark", layer: "atom", desc: "N [blob] RIGINS in Bowlby One caps, the logotype blob at 0.82em. In running text the name is lowercase Hanken 600 and never mixed with the lockup.", reads: "--ff-display · --ff-sans · currentColor", verdict: "Keep",
    note: "Correct in both forms. Sizes with <code>font-size</code> on the element, which is the right API for a mark.",
    demo: `<div class="rv-col" style="gap:20px">${wordmark(44)}${wordmark(22)}<p class="noo-body" style="margin:0">…and in a sentence it is <span class="noo-wordmark noo-wordmark--text">no origins</span>, nothing more.</p></div>` }),
  item({ name: "Glass", layer: "atom · surface", desc: "The surface primitive. <code>level</code> 1–3 and a <code>radius</code>; renders the recipe and nothing else. Everything translucent is built on it.", reads: "--glass-* · --surface · --shade · --e*", verdict: "Fix",
    note: "The component is right; its classes are the unprefixed ones (Tokens board). Also: a demo on a plain <code>--surface</code> is a grey box — the showcase’s catalogue does exactly that. Samples of glass belong on the ground, as here.",
    demo: `<div class="rv-row" style="gap:16px">${[["1","pill"],["2","lg"],["3","xl"]].map(([l,r]) => `<div class="glass glass-${l} noo-glass noo-r-${r}" style="padding:16px 22px"><span class="noo-body-sm">level ${l} · radius ${r}</span></div>`).join("")}</div>` }),
  item({ name: "Text", layer: "atom", desc: "Every run of words, at one of three steps: <code>lead</code> 19, <code>body</code> 16, <code>small</code> 14.5. One tone besides ink: muted.", reads: "type scale · --ink · --muted", verdict: "Fix",
    note: "The prop says <code>small</code>; the class says <code>body-sm</code>; the spec says <code>body-sm</code>. One vocabulary: rename the prop value to <code>body-sm</code> so a step has one name in the doc, the CSS and the API.",
    demo: `<div class="rv-col" style="gap:12px"><p class="noo-text noo-lead">A lead opens a section at nineteen over one and a half.</p><p class="noo-text noo-body">Body is sixteen over one point five five, the default for everything you read on the platform.</p><p class="noo-text noo-body-sm noo-text--muted">Small and muted is an aside — a caption, a date, a note under a card.</p></div>` }),
  item({ name: "Heading", layer: "atom", desc: "Levels 2, 3, 4. The Bowlby rule lives here: level 2 is the display face at 34; 3 and 4 are Hanken 600. Level 1 is deliberately absent — a surface has one h1 and it belongs to the page.", reads: "type scale", verdict: "Fix",
    note: "The ramp has display-1, display-2 and h1, and only <code>SectionHeader</code> can reach h1. Give <code>Heading</code> level 1 and a <code>display</code> size so the ramp has exactly one component, and let SectionHeader compose it instead of choosing class names itself.",
    demo: `<div class="rv-col" style="gap:14px"><h2 class="noo-heading noo-h2">Level 2 — the smallest Bowlby</h2><h3 class="noo-heading noo-h3">Level 3 — Hanken 600 at 26</h3><h4 class="noo-heading noo-h4">Level 4 — card titles at 21</h4><p class="rv-cap">not reachable from Heading today: display-1 72 · display-2 56 · h1 44</p></div>` }),
  item({ name: "Label", layer: "atom · the eyebrow", desc: "Twelve-pixel JetBrains Mono, uppercase, 0.1em tracking. The voice for metadata; one line, capped at 24 characters in the registry.", reads: "--ff-mono", verdict: "Keep",
    note: "Keep, and note the name collision: <code>Field</code> has a real <code>&lt;label&gt;</code> in 13px Hanken. Two things called label in one system; the form one should be spoken of as <em>field label</em> everywhere.",
    demo: `<div class="rv-col" style="gap:10px"><p class="noo-label" style="margin:0">the through-line</p><p class="noo-label" style="margin:0;color:var(--muted)">2019 — 2021 · hashnode</p><p class="noo-label" style="margin:0;color:var(--accent-deep)">project</p></div>` }),
  item({ name: "Dot", layer: "atom · a hue as a mark", desc: "A 12px disc in a hue’s deep tier. Exists because a hue survives the map zoom and text does not. Always decorative.", reads: "--{hue}-deep", verdict: "Keep",
    note: "Reads the hue slot once it exists and loses its ladder. The chip has its own 8px dot, <code>BlockCard</code> draws a third at 10px and the Rail’s group label a fourth at 6px — four dots, four sizes. One <code>Dot</code> with a <code>size</code>.",
    demo: `<div class="rv-row" style="gap:14px">${HUES.map((h) => `<span class="noo-dot" data-hue="${h}"></span>`).join("")}<span class="rv-cap" style="margin-left:8px">12 · 8 (chip) · 10 (BlockCard) · 6 (Rail group) — should be one</span></div>` }),
  item({ name: "Divider", layer: "atom", desc: "A hairline in <code>--rule</code>, as an <code>&lt;hr&gt;</code>. Dotted is the canvas voice — the region rule and the threads.", reads: "--rule", verdict: "Keep", note: "Nothing to change.",
    demo: `<div class="rv-col" style="gap:20px"><hr class="noo-divider"><hr class="noo-divider noo-divider--dotted"></div>` }),
  item({ name: "Image", layer: "atom · a photograph", desc: "A plain <code>&lt;img&gt;</code> with required <code>alt</code>, a <code>ratio</code> that reserves the box, fit and radius. Never <code>next/image</code> — optimisation is the host’s.", reads: "--r-*", verdict: "Fix",
    note: "<code>radius</code> offers none…xl but not <code>2xl</code>, the one radius that exists <em>for</em> large-format pictures. Take the whole radius scale.",
    demo: `<div class="rv-row" style="gap:16px">${["sm","md","lg","xl"].map((r) => `<img class="noo-img noo-img--r-${r}" src="${PHOTO}" alt="" width="112" height="112" style="object-fit:cover;aspect-ratio:1">`).join("")}<span class="rv-cap">radius sm · md · lg · xl — no 2xl</span></div>` }),
  item({ name: "Button", layer: "atom · action", desc: "A pill, 44 minimum, 36 small. Primary is ink on ground; secondary is glass-1 with its hairline; ghost is text with an underline on hover. Icon slots either side; <code>href</code> makes it a link.", reads: "--ink · --ground · glass-1 · --e1/--e2 · --r-pill", verdict: "Fix",
    note: "Sizes are 15 and 13.5 — neither on the scale — and heights are literals. Read <code>ui</code>/<code>ui-sm</code> and <code>--ctl-md</code>/<code>--ctl-sm</code>. Missing for the admin: an icon-only square (a close, a kebab) and a <code>danger</code> tone for the one destructive action a control surface has.",
    demo: `<div class="rv-col" style="gap:16px"><div class="rv-row">${btn("Say hello")}${btn("See the work","secondary")}${btn("Read more","ghost")}${btn("With a leading icon","primary","",`<span class="noo-btn__icon">${icon(SEARCH)}</span>`)}${btn("Next block","secondary","href",``).replace("</span></a>", `</span><span class="noo-btn__icon">${icon(ARROW)}</span></a>`)}</div><div class="rv-row">${btn("Small primary","primary","sm")}${btn("Small secondary","secondary","sm")}${btn("Small ghost","ghost","sm")}${btn("Focused","primary","focus")}${btn("Disabled","primary","disabled")}${btn("Disabled","secondary","disabled")}</div></div>` }),
  item({ name: "Chip", layer: "atom · mark", desc: "A 28px pill: the hue’s pastel at 45% over the surface, ink text, the deep tier as a dot. A button with <code>onClick</code>, a link with <code>href</code>; <code>pressed</code> is the selected filter.", reads: "--{hue} · --{hue}-deep · --surface", verdict: "Fix",
    note: "Reads the hue slot; loses its ladder. 13px → <code>ui-sm</code>, 28 → <code>--ctl-xs</code>. <code>Bento</code> restyles chips to 34/16 from the outside — that is a size, so it becomes <code>size=\"lg\"</code> on the chip rather than a rule about where it sits.",
    demo: `<div class="rv-col" style="gap:12px"><div class="rv-row" style="gap:8px">${HUES.map((h) => chip(h, h)).join("")}${chip("accent")}</div><div class="rv-row" style="gap:8px">${chip("no dot","lavender",{dot:false})}${chip("filter","peach",{interactive:true})}${chip("filter · pressed","peach",{interactive:true,pressed:true})}<span class="noo-chip" data-hue="blue" style="height:34px;padding-inline:14px;font-size:16px"><span class="noo-chip__dot"></span>bento size, 34</span></div></div>` }),
  item({ name: "Toggle", layer: "atom · control", desc: "A 44 × 26 switch. On: ink track, ground knob. Off: ink at 18% over the ground, surface knob. The hit area reaches 44 through a pseudo-element.", reads: "--ink · --ground · --surface · --e1", verdict: "Keep",
    note: "Keep. Track 26 becomes <code>--ctl-xs</code> 28 when the control tokens land, which also squares it with the chip.",
    demo: `<div class="rv-row" style="gap:28px"><label class="noo-toggle-row"><span>Breathing</span>${toggle(true)}</label><label class="noo-toggle-row"><span>Look at the pointer</span>${toggle(false)}</label><label class="noo-toggle-row is-disabled"><span>Disabled</span>${toggle(true,true)}</label></div>` }),
  item({ name: "Bubble", layer: "atom · speech", desc: "A glass-1 pill of real text — a <code>&lt;p&gt;</code> — 15/1.4 Hanken 500, padding 10 × 16, max 38ch. <code>tint</code> mixes a hue in; <code>pop</code> plays the spring on mount.", reads: "glass-1 · --{hue} · --surface", verdict: "Keep",
    note: "Reads the hue slot; loses its ladder. 15px maps to <code>ui</code>. Anchoring stays the layout’s job.",
    demo: `<div class="rv-row" style="gap:12px"><p class="glass glass-1 noo-bubble">What are we doing today?</p><p class="glass glass-1 noo-bubble noo-bubble--tint" data-hue="peach">Start with the portfolio.</p><p class="glass glass-1 noo-bubble noo-bubble--tint" data-hue="blue">I’m the agents harness, and this bubble wraps when it has more to say than fits on a line.</p></div>` }),
  item({ name: "Card", layer: "atom · surface", desc: "Solid <code>--surface</code> with e1, or glass-1. Radius 20, padding 24 or 20. <code>interactive</code> lifts a level and a pixel on hover.", reads: "--surface · --e1/--e2 · --r-lg · glass-1", verdict: "Fix",
    note: "Padding literals → <code>--s-6</code> / <code>--s-5</code>, and add <code>lg</code> (40): <code>Quote</code> is a Card at 40 with its own CSS today. Card is the surface every organism should stand on rather than re-declare.",
    demo: `<div class="rv-row rv-row--start" style="gap:16px"><div class="noo-card" style="width:220px"><p class="noo-label" style="margin:0 0 8px;color:var(--muted)">solid</p><p class="noo-h4" style="margin:0 0 6px">A surface card</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">Padding 24, e1, radius 20.</p></div><div class="noo-card glass glass-1 noo-card--glass" style="width:220px"><p class="noo-label" style="margin:0 0 8px;color:var(--muted)">glass</p><p class="noo-h4" style="margin:0 0 6px">A glass card</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">Over the grid. For panels the platform should show through.</p></div><div class="noo-card noo-card--pad-sm noo-card--interactive" style="width:220px;transform:translateY(-1px);box-shadow:var(--e2)"><p class="noo-label" style="margin:0 0 8px;color:var(--muted)">interactive · hovered</p><p class="noo-h4" style="margin:0 0 6px">Lifted</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">e1 → e2 and one pixel. Padding 20.</p></div></div>` }),
  item({ name: "Placeholder", layer: "atom · the honest empty state", desc: "A dashed box saying what will be here and why it is not. <code>draft</code> adds a tag and an accent border so scaffolding is never mistaken for writing. Never “coming soon”.", reads: "--rule · --accent-deep · --accent-tint", verdict: "Keep",
    note: "A brand component, not a generic one — keep it. The tag’s 11px mono is off the scale; it is a <code>label</code> at 12.",
    demo: `<div class="rv-row rv-row--start" style="gap:16px"><div class="noo-placeholder noo-placeholder--draft" style="width:300px"><span class="noo-placeholder__tag">draft</span><p class="noo-h4 noo-placeholder__title">Case studies</p><div class="noo-body-sm noo-placeholder__body">Problem → approach → outcome, three of them. Not written yet.</div></div><div class="noo-placeholder" style="width:300px"><p class="noo-h4 noo-placeholder__title">Nothing shipped yet</p><div class="noo-body-sm noo-placeholder__body">Everything was deleted for a clean slate. This fills as things ship.</div></div></div>` }),
  item({ name: "Stack · Row", layer: "atom · layout", desc: "Things down the page; things across, wrapping. Gap is one of four steps — 8, 16, 24, 40 — and nothing between. Spacing belongs to the container, never the child.", reads: "the space scale (as literals today)", verdict: "Keep",
    note: "These two are why an app never needs a utility class for layout. Map the four gaps to <code>--s-2 · --s-4 · --s-6 · --s-10</code> and they are finished.",
    demo: `<div class="rv-row rv-row--start" style="gap:32px"><div class="noo-stack noo-stack--g8"><span class="rv-box">stack · gap 8</span><span class="rv-box">two</span><span class="rv-box">three</span></div><div class="noo-stack noo-stack--g24"><span class="rv-box">stack · gap 24</span><span class="rv-box">two</span></div><div class="noo-row noo-row--g16 noo-row--center" style="width:260px"><span class="rv-box">row · gap 16</span><span class="rv-box">wraps</span><span class="rv-box">when it runs out</span><span class="rv-box">of room</span></div></div>` }),
  item({ name: "Illustration", layer: "atom · figure", desc: "A named picture drawn by code from one generator: fine lines, one hue, one weight, none touching. Placed top-right of a cell, as a field across it, or alone.", reads: "--{hue}-tint · currentColor", verdict: "Keep",
    note: "Governed by Illustrations.md; nothing here overrides it. Reads the hue slot once it exists. Shown as a stand-in: the real one needs the generator at runtime.",
    demo: `<div class="rv-row" style="gap:20px"><div class="noo-bento" data-hue="peach" style="padding:0"><div class="noo-bento__cell noo-bento__cell--fill" style="grid-column:span 2;grid-row:span 2;width:304px;height:304px">${illo()}<p class="noo-label" style="margin:0">work</p><p class="noo-bento__figure"><span class="noo-bento__value">4</span><span class="noo-label noo-bento__figure-label">roles</span></p></div></div><p class="rv-cap" style="max-width:24ch">a field drawing behind the diagonal: label top-left, figure bottom-left</p></div>` }),
  item({ name: "Icon", layer: "atom · missing", desc: "There is no icon layer. Button, Chip and Field have slots for one, and the package draws two arrows and a magnifier inline to fill them. Your note: “we are still missing icons.”", reads: "--icon-sm/md/lg ✚ · --icon-stroke ✚ · currentColor", verdict: "Missing",
    note: "An <code>Icon</code> atom with three sizes and one stroke weight, sourced from one set behind one component. Five weights and five sources are on the Icons board; decision D8.",
    demo: `<div class="rv-row" style="gap:16px">${["home","search","folder","message","plus","pin","sliders","user","archive","heart"].map((n) => ico(n,"regular",24)).join("")}</div>` }),
  item({ name: "Focus · skip · sr-only", layer: "atom · accessibility", desc: "One focus ring for everything that takes focus: 2px <code>--accent-deep</code>, 2px out. A skip link that appears on focus. A visually-hidden class for the heading a canvas needs.", reads: "--accent-deep · --ink · --ground", verdict: "Fix",
    note: "The ring is declared twice — once with <code>:where()</code> for every element, once again for a list of component classes. The first rule already covers the second; delete the duplicate.",
    demo: `<div class="rv-row" style="gap:20px"><a class="noo-skip" href="#" style="position:static;top:auto;left:auto">Skip to content</a><button type="button" class="noo-btn noo-btn--secondary glass glass-1 noo-btn--sm rv-focus">focused</button><span class="noo-chip noo-chip--interactive rv-focus" data-hue="green"><span class="noo-chip__dot"></span>focused chip</span><span class="rv-cap">::selection is the block tint</span></div>` }),
];

export const title = "Atoms";
export const block = "portfolio";
export const body = `
${head({ eyebrow: "release review · layer 2 of 6", title: "Atoms", lead: "The nineteen things that do one job and contain nothing of their own kind. Each sample is the package’s own markup and CSS. Most are right; the fixes are about what they read — sizes and hues as literals where a token should be — not about how they look." })}
${legend()}
${items.join("")}
`;
