import { head, legend, group, item, blob, chip, icon, SEARCH, ARROW } from "../lib.mjs";

const field = ({ label, placeholder, hint, error, lead, trail, multiline, value }) => `<div class="noo-field${multiline ? " noo-field--multiline" : ""}${error ? " noo-field--invalid" : ""}" style="width:300px"><label class="noo-field__label">${label}</label><div class="noo-glass noo-glass--1 noo-field__box">${lead ? `<span class="noo-field__adorn">${lead}</span>` : ""}${multiline ? `<textarea class="noo-field__input" rows="3" placeholder="${placeholder ?? ""}"></textarea>` : `<input class="noo-field__input" placeholder="${placeholder ?? ""}"${value ? ` value="${value}"` : ""}>`}${trail ? `<span class="noo-field__adorn">${trail}</span>` : ""}</div>${error ? `<p class="noo-field__error">${error}</p>` : hint ? `<p class="noo-field__hint">${hint}</p>` : ""}</div>`;

const segmented = (opts, on, label = "Choose") => `<div class="noo-glass noo-glass--1 noo-segmented" role="group" aria-label="${label}">${opts.map((o) => `<button type="button" class="noo-segmented__btn"${o === on ? ' aria-pressed="true"' : ""}>${o}</button>`).join("")}</div>`;

const CHEVRON = `<svg class="noo-field__chevron" viewBox="0 0 16 16" aria-hidden="true"><path d="M4 6l4 4 4-4" style="fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round"/></svg>`;
const select = ({ label, placeholder, options, hint }) => `<div class="noo-field noo-field--select" style="width:300px"><label class="noo-field__label">${label}</label><div class="noo-glass noo-glass--1 noo-field__box"><select class="noo-field__input noo-field__select">${placeholder ? `<option value="" disabled selected>${placeholder}</option>` : ""}${options.map((o) => `<option>${o}</option>`).join("")}</select><span class="noo-field__adorn">${CHEVRON}</span></div>${hint ? `<p class="noo-field__hint">${hint}</p>` : ""}</div>`;
const check = ({ label, hint, on, radio, mixed }) => `<label class="noo-check${radio ? " noo-check--radio" : ""}"><input type="${radio ? "radio" : "checkbox"}" class="noo-check__input"${on ? " checked" : ""}${mixed ? ' data-mixed' : ""}>` +
  `<span class="noo-check__box" aria-hidden="true">${radio ? '<span class="noo-check__dot"></span>' : '<svg viewBox="0 0 16 16" class="noo-check__mark"><path class="noo-check__tick" d="M3.5 8.5l3 3 6-6"/><path class="noo-check__dash" d="M4 8h8"/></svg>'}</span>` +
  `<span class="noo-check__text"><span class="noo-check__label">${label}</span>${hint ? `<span class="noo-check__hint">${hint}</span>` : ""}</span></label>`;
const tabs = (names, on, panel) => `<div class="noo-tabs" style="width:420px"><div role="tablist" aria-label="Token groups" class="noo-tabs__list">${names.map((n) => `<button type="button" role="tab" class="noo-tabs__tab" aria-selected="${n === on}"${n === on ? "" : ' tabindex="-1"'}>${n}</button>`).join("")}</div><div role="tabpanel" class="noo-tabs__panel noo-body-sm">${panel}</div></div>`;
const toast = (tone, title, text, close = false) => `<div role="status" class="noo-glass noo-glass--2 noo-toast noo-toast--${tone}" style="width:360px"><span class="noo-toast__mark" aria-hidden="true"></span><div class="noo-toast__body"><p class="noo-toast__title">${title}</p><p class="noo-toast__text">${text}</p></div>${close ? '<button type="button" class="noo-toast__close" aria-label="Dismiss"><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M4 4l8 8M12 4l-8 8" style="fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round"/></svg></button>' : ""}</div>`;
const tooltip = (side, text, trigger) => `<span class="noo-tip noo-tip--${side} is-open">${trigger}<span role="tooltip" class="noo-tip__bubble">${text}</span></span>`;

const steps = (across = false) => `<ol class="noo-steps${across ? " noo-steps--across" : ""}" data-hue="lavender">${[["Discover","A form and a schedule. Audit, define, plan."],["Design","Build the block, shaped by the type scale."],["Ship","The registry entry, then the catalogue."]].map(([t,b]) => `<li class="noo-step"><span class="noo-step__marker" aria-hidden="true"></span><div class="noo-step__body"><p class="noo-h4 noo-step__title">${t}</p><div class="noo-body-sm noo-step__text">${b}</div></div></li>`).join("")}</ol>`;

export const items = [
  item({ name: "Field", layer: "molecule · label + box + hint", desc: "A field label in caption, a glass-1 box at 48 holding the control, a hint or an error under it. Focus is 1.5px accent-deep inside and 3px accent at 25% outside; error turns the ring <code>--bad</code> and is announced.", reads: "glass-1 · --r-md · --accent* · --bad · --muted", verdict: "Fix",
    note: "Right as a text field. It is the <em>only</em> form control besides Toggle, and the admin’s settings and inspector need Select, Checkbox and Radio — each of which should wear this exact box and label. Height 48 sits between <code>--ctl-md</code> 44 and <code>--ctl-lg</code> 56; pick 44 to match the button beside it. <b>Done:</b> the frame is <code>FieldShell</code>, which <code>Field</code> and <code>Select</code> both wear.",
    demo: `<div class="rv-row rv-row--start" style="gap:20px">${field({ label: "Name", placeholder: "What should the blobs call you?" })}${field({ label: "Email", placeholder: "you@somewhere.com", hint: "Only for the reply. Never shared." })}${field({ label: "Handle", value: "no origins", error: "Handles can’t contain spaces." })}${field({ label: "Search", placeholder: "Search the blocks", lead: icon(SEARCH) })}${field({ label: "Site", placeholder: "bhargav", lead: "https://", trail: ".no-origins.com" })}${field({ label: "Message", placeholder: "Say what’s on your mind.", multiline: true })}</div>` }),
  item({ name: "Segmented (ThemeSwitch is an instance)", layer: "molecule · glass-1 pill of buttons · built 2026-09-14", desc: "Light · system · dark in a glass-1 pill; the pressed one is ink on ground. Reads and writes <code>&lt;html data-theme&gt;</code>.", reads: "glass-1 · --ink · --ground · --ink-2", verdict: "Merge",
    note: "It is a segmented control that happens to switch themes. The admin footer bar needs three more of these (desktop/mobile, grid on/off, block accent). Generalise to <code>Segmented</code>; <code>ThemeSwitch</code> becomes an instance with the theme wiring. Buttons 28 → <code>--ctl-xs</code>. <b>Done:</b> <code>Segmented</code> ships with <code>sm</code>/<code>md</code>; <code>.noo-theme</code> is an alias for one release.",
    demo: `<div class="rv-row" style="gap:20px">${segmented(["Light","System","Dark"],"System","Theme")}${segmented(["Desktop","Phone"],"Desktop","Viewport")}${segmented(["Grid","Off"],"Grid","Grid")}</div>` }),
  item({ name: "ChatInput", layer: "molecule · bar + input + send + chips", desc: "A glass-2 pill, 56 tall, the send button a 36px accent circle with the blob’s eyes. Suggestions render as chips above it — the guided menu until the harness answers for itself.", reads: "glass-2 · --accent · --eye · --r-pill · Chip", verdict: "Keep",
    note: "Keep. The bar is <code>--ctl-lg</code>, the send button <code>--ctl-sm</code>; the input’s 16px is <code>body</code>. Already composed from atoms the right way round.",
    demo: `<form class="noo-chat"><div class="noo-chat__suggestions">${[["Who are you?","peach"],["Show me the work","green"],["What are you after?","blue"],["How do you think?","lavender"]].map(([l,h]) => chip(l,h,{interactive:true,dot:false})).join("")}</div><div class="glass glass-2 noo-chat__bar"><input class="noo-chat__input" placeholder="Hey! What's on your mind today?"><button type="button" class="noo-chat__send" aria-label="Send"><svg viewBox="0 0 36 20" aria-hidden="true"><circle cx="11" cy="10" r="4.5" fill="currentColor"/><circle cx="25" cy="10" r="4.5" fill="currentColor"/></svg></button></div></form>` }),
  item({ name: "SectionHeader · Intro · CellHead", layer: "molecule · heading groups · merged 2026-09-14", desc: "Three components that are a heading with something above or below it. <code>SectionHeader</code>: eyebrow + title + lead + rhythm (64 above, 32 below). <code>Intro</code>: title + lead, no rhythm. <code>CellHead</code>: eyebrow + 22px title + dot, at widget scale.", reads: "Heading · Text · Label · Dot", verdict: "Merge",
    note: "Two of these are the same object. Fold <code>Intro</code> into <code>SectionHeader</code> — it is SectionHeader with <code>rhythm={false}</code> and no eyebrow — and let SectionHeader compose <code>Heading</code> rather than pick class names itself. <code>CellHead</code> stays: the widget ramp is a different scale, and folding it in would put a 22px size on the document component. <b>Done:</b> <code>SectionHeader</code> takes <code>rhythm</code> and composes Label, Heading and Text; <code>Intro</code> is a deprecated alias.",
    demo: `<div class="rv-row rv-row--start" style="gap:40px"><header class="noo-section-header" style="margin:0;width:340px"><p class="noo-label noo-section-header__label">the registry</p><h2 class="noo-h2 noo-section-header__title">Four roles, told as blocks</h2><p class="noo-lead noo-section-header__lead">Editors, design systems, agents and shipping full-stack.</p></header><header class="noo-section-header noo-section-header--flush" style="width:300px"><h2 class="noo-heading noo-h2 noo-section-header__title">Hi, I’m Bhargav.</h2><p class="noo-text noo-lead noo-section-header__lead">I build editors, design systems and agent tools.</p></header><div class="noo-cellhead" style="width:200px"><p class="noo-label">now</p><p class="noo-bento__title noo-cellhead__title"><span class="noo-dot" data-hue="peach"></span>Radise</p></div></div>` }),
  item({ name: "Figure", layer: "molecule · value + label", desc: "A number or a short word as image — the display face at 96 or 56 with a mono label under it. Honest counts only: <code>4</code> roles, <code>0</code> shipped yet.", reads: "--ff-display · Label", verdict: "Fix",
    note: "Exported as <code>BentoFigure</code>, registered as <code>Figure</code>. One name — <code>Figure</code> — and the widget sizes become the two widget type tokens.",
    demo: `<div class="rv-row" style="gap:48px;align-items:flex-end"><p class="noo-bento__figure"><span class="noo-bento__value">4</span><span class="noo-label noo-bento__figure-label">roles</span></p><p class="noo-bento__figure noo-bento__figure--md"><span class="noo-bento__value">0</span><span class="noo-label noo-bento__figure-label">shipped yet</span></p><p class="noo-bento__figure noo-bento__figure--md"><span class="noo-bento__value">3</span><span class="noo-label noo-bento__figure-label">worth telling</span></p></div>` }),
  item({ name: "Steps", layer: "molecule · numbered sequence", desc: "An ordered list with a CSS counter — reorder the steps and they renumber — and a rule drawn by each step so it stops at the last without counting. Down, or across from 640.", reads: "--{hue}-deep · --surface · --rule · --e1", verdict: "Keep",
    note: "Reads the hue slot; loses its ladder. Use only where order is real.",
    demo: `<div class="rv-col" style="gap:32px"><div style="width:420px">${steps()}</div>${steps(true)}</div>` }),
  item({ name: "Speaker", layer: "molecule · built 2026-09-14", desc: "A blob with its bubble anchored top-right at an 8px gap. The canvas does it inside <code>BlobNode</code>; the fixtures and the About panel do it by hand every time.", reads: "Blob · Bubble", verdict: "Missing",
    note: "The pairing the brand is built on has no name. One component, <code>Speaker</code>, that <code>BlobNode</code> renders on the canvas and anyone can place in a page. <b>Built</b> in step 4.",
    demo: `<div class="rv-row" style="gap:48px;align-items:flex-end"><div style="display:flex;align-items:flex-end;gap:8px">${blob({ size: "md", host: true })}<p class="glass glass-1 noo-bubble" style="margin-bottom:34px">What are we doing today?</p></div><div style="display:flex;align-items:flex-end;gap:8px">${blob({ size: "md", hue: "green" })}<p class="glass glass-1 noo-bubble noo-bubble--tint" data-hue="green" style="margin-bottom:34px">Hey there!!</p></div></div>` }),
  item({ name: "Dots", layer: "molecule · pagination · built 2026-09-14", desc: "The row of dots under a Carousel; the current one stretches to 26. Reached 44px through a pseudo-element.", reads: "--ink · --r-pill", verdict: "Merge",
    note: "<code>Deck</code> reaches into <code>.noo-carousel__dot</code> to reuse it, which is a smell with a fix: a <code>Dots</code> molecule both organisms render. <b>Done.</b>",
    demo: `<div class="noo-dots" role="tablist" aria-label="Quotes — choose one"><button type="button" role="tab" class="noo-dots__dot" aria-selected="true" aria-label="Slide 1 of 4"></button><button type="button" role="tab" class="noo-dots__dot" aria-label="Slide 2 of 4"></button><button type="button" role="tab" class="noo-dots__dot" aria-label="Slide 3 of 4"></button><button type="button" role="tab" class="noo-dots__dot" aria-label="Slide 4 of 4"></button></div>` }),
  item({ name: "Contrast row", layer: "molecule · moved 2026-09-14", desc: "One measured text-on-surface pair: swatch, name, ratio, floor; a red outline when it fails. The report is what makes a broken floor impossible to miss.", reads: "--ground-2 · --bad · --ff-mono", verdict: "Fix",
    note: "The CSS is in the package (<code>.noo-contrast__*</code>) but the component lives in <code>apps/design</code>. Half a fork. The admin needs the same report, so move <code>ContrastReport</code> into the package beside <code>Catalogue</code>. <b>Done:</b> <code>@no-origins/ui/registry</code> exports it; the showcase imports it from there.",
    demo: `<div class="noo-contrast" style="width:520px">${[["ink on ground","11.74:1","8",false,"var(--ground)","var(--ink)"],["muted on ground","4.20:1","4.5",true,"var(--ground)","var(--muted)"],["peach-deep on ground","6.72:1","4.5",false,"var(--ground)","var(--peach-deep)"],["blue-ink on blue","4.05:1","4.5",true,"var(--blue)","var(--blue-ink)"]].map(([n,r,f,fail,bg,fg]) => `<div class="noo-contrast__row"${fail ? " data-fail" : ""}><span class="noo-contrast__chip" style="background:${bg};color:${fg}">Aa</span><span class="noo-contrast__name">${n}</span><span class="noo-contrast__num">${r}</span><span class="noo-contrast__floor">floor ${f}</span></div>`).join("")}</div>` }),
];

const MISSING = [
  ["Dialog · Sheet", "glass-3 — the first consumer the level has ever had. Radius xl, e4, one primary action.", "confirm publish · product install"],
  ["Menu", "One organism (D9): column · rail · two columns · floating · sheet. Step 4.", "the admin’s nav · the canvas"],
  ["Tree", "Rail’s list grammar with disclosure; DOM order is tab order.", "the editor outline"],
  ["Speaker", "Blob + Bubble, named. Step 4, with BlobNode.", "the canvas · the About panel"],
];

const built = [
  item({ name: "Select", layer: "molecule · built 2026-09-14", desc: "A native <code>&lt;select&gt;</code> in the <code>FieldShell</code>; the chevron is a trailing adornment that clicks through. Flat or grouped options; a <code>placeholder</code> renders as a disabled first option so an untouched select reads as empty.", reads: "FieldShell · --icon-sm · --ink-2", verdict: "Missing",
    note: "Native on purpose: the OS picker is the control every reader already knows on a phone. <b>Built.</b>",
    demo: `<div class="rv-row rv-row--start" style="gap:20px">${select({ label: "Block", placeholder: "Choose a block", options: ["Portfolio · peach", "Design system · blue", "Admin · lavender"], hint: "Each block owns one hue." })}${select({ label: "Hue", options: ["peach", "lavender", "blue", "green", "pink", "yellow", "grey"] })}</div>` }),
  item({ name: "Checkbox · Radio · RadioGroup", layer: "molecule · built 2026-09-14", desc: "A native input wearing a 20px box: surface with the hairline off, ink with a ground mark on. Same anatomy — box, label, hint — the radio’s corners rounded all the way. <code>RadioGroup</code> is the fieldset that supplies one <code>name</code> and a legend.", reads: "--surface · --ink · --ground · --glass-border · --e1 · --t-ui · --t-caption", verdict: "Missing",
    note: "<code>appearance: none</code>, never <code>display: none</code>: the keyboard, the form and the screen reader get the real control; the box is what the eye gets. <b>Built.</b>",
    demo: `<div class="rv-row rv-row--start" style="gap:40px"><div class="rv-col" style="gap:10px">${check({ label: "Show the grid", hint: "The 144px box grid the canvas snaps to.", on: true })}${check({ label: "Snap to it" })}${check({ label: "Publish on save", hint: "Off while the editor is a draft." })}</div><fieldset class="noo-radiogroup"><legend class="noo-field__label noo-radiogroup__legend">Publish as</legend><div class="noo-radiogroup__options">${check({ radio: true, label: "Draft", hint: "Saved, visible only to you.", on: true })}${check({ radio: true, label: "Live", hint: "Revalidates the site within a minute." })}</div></fieldset></div>` }),
  item({ name: "Tabs", layer: "molecule · built 2026-09-14", desc: "Ghost buttons on a hairline; the current one wears the NavBar’s marker — 2px <code>--accent-deep</code> underneath. Arrow keys and Home/End move and activate; inactive panels are <code>hidden</code>, not unmounted.", reads: "--rule · --accent-deep · --ctl-md · --t-ui", verdict: "Missing",
    note: "The WAI-ARIA tabs pattern, hand-rolled: forty lines, no peer. <b>Built.</b>",
    demo: tabs(["Colour", "Type", "Space"], "Type", "Bowlby from h2 up; Hanken 600 and 400 below.") }),
  item({ name: "Toast", layer: "molecule · built 2026-09-14", desc: "glass-2, radius lg, a 3px mark and a 9% wash in the semantic colour behind the text. <code>good</code> · <code>warn</code> · <code>bad</code> · <code>neutral</code>; <code>bad</code> is <code>role=alert</code>, the rest <code>status</code>. <code>ToastStack</code> is where they land.", reads: "glass-2 · --r-lg · --good · --warn · --bad · --ink", verdict: "Missing",
    note: "Presentational: whoever shows it owns the timer and the list. One action at most — a toast with two buttons is a dialog that got lost. <b>Built.</b>",
    demo: `<div class="rv-col" style="gap:10px">${toast("good", "Published", "The site will catch up within a minute.", true)}${toast("warn", "Saved, not published", "Version 12 is yours until you say otherwise.")}${toast("bad", "Couldn’t publish", "The webhook answered 500. Nothing changed on the site.")}${toast("neutral", "Draft saved", "Two minutes ago.")}</div>` }),
  item({ name: "Tooltip", layer: "molecule · built 2026-09-14", desc: "Ink on ground, caption size, radius sm. Text only. Describes its child (<code>aria-describedby</code>), so the child must be focusable; shows on hover and focus, hides on Escape. Never portalled.", reads: "--ink · --ground · --t-caption · --r-sm · --e2", verdict: "Missing",
    note: "A tooltip that needs a link or a picture is a popover, and the platform does not have one yet. <b>Built.</b>",
    demo: `<div class="rv-row" style="gap:64px;padding:40px 0 20px">${tooltip("top", "Revalidates the live site", '<button type="button" class="noo-btn noo-btn--secondary noo-btn--sm noo-glass noo-glass--1"><span class="noo-btn__text">Publish</span></button>')}${tooltip("right", "Only for the reply. Never shared.", '<button type="button" class="noo-btn noo-btn--ghost noo-btn--sm"><span class="noo-btn__text">Why?</span></button>')}${tooltip("bottom", "Peach is the portfolio’s hue", chip("peach", "peach", { interactive: true }))}</div>` }),
];

export const title = "Molecules";
export const block = "editor";
export const body = `
${head({ eyebrow: "release review · layer 3 of 6", title: "Molecules", lead: "Atoms combined into one thing with one job. Nine exist. Three of them are the same object under different names, and eight the admin needs do not exist yet — which is the point: the admin is the forcing function for the system’s second half." })}
${legend()}
${items.join("")}
${group("Built in step 3 — the admin’s first seven", "Admin.md §10 listed them. Each is composed from atoms that exist and reads tokens that exist; none needed a new colour, radius or size — and none needed a headless peer: a native control or forty lines of ARIA did it. Every one is registered, so the catalogue shows it in the showcase and the admin at once.")}
${built.join("")}
${group("Built in step 4", "The four that were left: Dialog and Sheet on a native <dialog> (the top layer, the focus trap, Escape and the backdrop come from the platform, so no peer); Menu as D9 says; Tree as the editor's outline; Speaker beside BlobNode. All on the Organisms board.")}
${item({ name: "Four more", layer: "built 2026-09-14", desc: "Dialog and Sheet are the first consumers glass-3 has ever had; Menu is D9; Tree is the editor outline.", verdict: "Missing", note: "<b>Built</b> in step 4 — see the Organisms board for the samples.", wide: true, tight: true,
  demo: `<table class="rv-table"><tr><th>component</th><th>anatomy, in tokens</th><th>first consumer</th></tr>${MISSING.map(([n,a,c]) => `<tr><td>${n}</td><td>${a}</td><td>${c}</td></tr>`).join("")}</table>` })}
`;
