import { head, legend, group, item, blob, wordmark, chip, illo, PHOTO, icon, ico, ARROW } from "../lib.mjs";

export const themeSwitch = () => `<div class="noo-glass noo-glass--1 noo-segmented" role="group" aria-label="Theme"><button type="button" class="noo-segmented__btn">Light</button><button type="button" class="noo-segmented__btn" aria-pressed="true">System</button><button type="button" class="noo-segmented__btn">Dark</button></div>`;

const navbar = () => `<header class="glass glass-2 noo-nav" style="position:static"><a href="#" class="noo-skip">Skip to content</a><div class="noo-container noo-nav__inner"><a href="#" class="noo-nav__home">${wordmark(22)}</a><nav class="noo-nav__links"><a href="#" class="noo-nav__link" aria-current="page">Overview</a><a href="#" class="noo-nav__link">Components</a><a href="#" class="noo-nav__link">Tokens</a></nav><div class="noo-nav__trailing">${themeSwitch()}</div></div></header>`;

const mi = (label, opts = {}) => `<li class="noo-menu__item"><div class="noo-menu__row"><a href="#" class="noo-menu__link"${opts.current ? ' aria-current="page"' : ""}>${opts.icon ? `<span class="noo-menu__icon" aria-hidden="true">${ico(opts.icon, "regular", 20)}</span>` : ""}<span class="noo-menu__label">${label}</span>${opts.badge ? `<span class="noo-menu__badge">${opts.badge}</span>` : ""}</a></div>${opts.children ? `<ul class="noo-menu__list noo-menu__list--sub">${opts.children}</ul>` : ""}</li>`;
const mg = (items, label, hue) => `<div class="noo-menu__group"${hue ? ` data-hue="${hue}"` : ""}>${label ? `<p class="noo-label noo-menu__group-label"><span class="noo-menu__group-dot" aria-hidden="true"></span>${label}</p>` : ""}<ul class="noo-menu__list">${items}</ul></div>`;
export const rail = (h = 600, form = "column") => `<nav class="noo-glass noo-glass--2 noo-menu noo-menu--${form}" aria-label="Primary" style="position:static;height:${h}px;margin:0;flex:none"><div class="noo-menu__col"><div class="noo-menu__brand"><a href="#" class="noo-menu__home">${wordmark(20)}</a></div><div class="noo-menu__groups">
${mg(mi("Overview", { icon: "home" }))}
${mg(mi("All projects", { icon: "folder" }), "Projects", "peach")}
${mg(mi("All systems", { icon: "layers", current: true, children: mi("Design System", { current: true }) + mi("Document") + mi("Publishing") + mi("Storage") }), "Systems", "lavender")}
${mg(mi("All products", { icon: "grid", badge: "2" }), "Products", "blue")}
</div><div class="noo-menu__trailing">${themeSwitch()}<p class="noo-text noo-body-sm noo-text--muted" style="padding:0 12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">bhargav@no-origins.com</p><button type="button" class="noo-menu__link">Sign out</button></div></div></nav>`;

const footer = () => `<footer class="noo-footer" style="margin-top:0"><div class="noo-container noo-footer__inner"><div class="noo-footer__brand"><span class="noo-wordmark noo-wordmark--text noo-footer__name">no origins</span><p class="noo-footer__meta">design.no-origins.com</p></div><nav class="noo-footer__links"><a href="#" class="noo-footer__link">Overview</a><a href="#" class="noo-footer__link">Components</a><a href="#" class="noo-footer__link">Tokens</a></nav><div class="noo-footer__trailing">${themeSwitch()}</div></div></footer>`;

const blockCard = () => `<article class="noo-card noo-block-card noo-block-card--dot" data-hue="peach" style="width:440px"><span class="noo-block-card__hue" aria-hidden="true"></span><div class="noo-block-card__body"><p class="noo-label noo-block-card__meta">hashnode · one year</p><h3 class="noo-h4 noo-block-card__title">Neptune, Hashnode’s editor</h3><p class="noo-body-sm noo-block-card__line">The tiptap editor: foundational blocks and an OpenAI integration. Core team on the design system.</p><ul class="noo-body-sm noo-block-card__details"><li>Owned the editor end to end</li><li>Shipped the design system with the core team</li></ul><div class="noo-block-card__chips">${chip("editor","peach")}${chip("design systems","peach")}${chip("react","peach")}</div></div></article>`;
const roadmapItem = () => `<article class="noo-card noo-block-card noo-block-card--dot noo-block-card--sleep" data-hue="lavender" style="width:440px"><span class="noo-block-card__hue" aria-hidden="true"></span><div class="noo-block-card__body"><h3 class="noo-h4 noo-block-card__title">An editor to write and publish</h3><p class="noo-body-sm noo-block-card__line">Not here yet. Articles as documents on the canvas, published with a version number.</p><p class="noo-label noo-block-card__progress">designing</p></div></article>`;

const mediaCard = () => `<article class="noo-media-card noo-media-card--beside" data-hue="lavender" style="width:640px"><div class="noo-media-card__media noo-textured"></div><div class="noo-media-card__body"><p class="noo-label noo-media-card__meta">case study · 2025</p><p class="noo-h4 noo-media-card__title">The rise of ambient computing</p><p class="noo-body noo-media-card__line">Two production editors on tiptap; the second one taught the first one’s lessons.</p><div class="noo-media-card__footer">${chip("editor","lavender")}<a class="noo-btn noo-btn--primary noo-btn--sm" href="#"><span class="noo-btn__text">Read</span></a></div></div></article>`;

const quote = () => `<figure class="noo-card noo-card--pad-lg noo-card--r-xl noo-quote" style="width:560px"><div class="noo-quote__words"><p class="noo-quote__figure"><span class="noo-quote__value">4</span><span class="noo-label noo-quote__figure-label">roles, one line</span></p><blockquote class="noo-quote__text noo-h3">Editors, design systems, agent systems, and shipping full-stack.</blockquote><figcaption class="noo-quote__by"><span class="noo-quote__name">Bhargav</span><span class="noo-quote__role noo-body-sm">No Origins</span></figcaption></div></figure>`;

const profile = (w = 300, hue = "peach") => `<article class="noo-profile noo-profile--fill" data-hue="${hue}" style="width:${w}px"><div class="noo-profile__bloom" aria-hidden="true"><img src="${PHOTO}" alt=""></div><div class="noo-profile__card"><div class="noo-profile__media"><img src="${PHOTO}" alt=""></div><div class="noo-profile__frost" aria-hidden="true"><img src="${PHOTO}" alt=""></div><span class="noo-profile__sheen" aria-hidden="true"></span><div class="noo-profile__words"><p class="noo-profile__name">Bhargav</p><p class="noo-profile__role">Software Engineer</p></div></div></article>`;

const deck = () => `<div class="noo-deck" style="--deck-visible:1;--deck-overlap:0.28;width:760px"><div class="noo-deck__track" role="group" aria-label="The team">${[0,1,2].map((i) => `<div class="noo-deck__slide" style="--ad:${i};z-index:${100-i*10}">${profile(420, ["peach","lavender","blue"][i])}</div>`).join("")}</div><div class="noo-dots noo-deck__dots" role="tablist"><button class="noo-dots__dot" aria-selected="true"></button><button class="noo-dots__dot"></button><button class="noo-dots__dot"></button></div></div>`;

const carousel = () => `<div class="noo-carousel" style="width:760px"><div class="noo-carousel__track noo-carousel__track--peek-md noo-carousel__track--g24" role="group" aria-label="Quotes">${["Planning to be guesswork.","It reads like on time, not five.","The registry is the palette."].map((t,i) => `<div class="noo-carousel__slide"><div class="noo-card"><p class="noo-h4" style="margin:0 0 8px">${t}</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">Slide ${i+1} of 3 — the neighbour peeks, so you know there is one.</p></div></div>`).join("")}</div><div class="noo-dots noo-carousel__dots" role="tablist"><button class="noo-dots__dot" aria-selected="true"></button><button class="noo-dots__dot"></button><button class="noo-dots__dot"></button></div></div>`;

const cell = (tone, span, inner, extra = "") => `<div class="noo-bento__cell${tone === "glass" ? " glass glass-1" : ""} noo-bento__cell--${tone}" style="grid-column:span ${span[0]};grid-row:span ${span[1]};${extra}">${inner}</div>`;
export const bento = () => `<div class="noo-bento" data-hue="peach" role="group" aria-label="Work experience" style="--bento-cols:4;--bento-rows:3">
${cell("fill",[2,2],`${illo()}<p class="noo-label" style="margin:0">work</p><p class="noo-bento__figure"><span class="noo-bento__value">4</span><span class="noo-label noo-bento__figure-label">roles</span></p>`)}
${cell("quiet",[1,1],`<div class="noo-cellhead"><p class="noo-label">now</p><p class="noo-bento__title noo-cellhead__title"><span class="noo-dot" data-hue="peach"></span>Radise</p></div>`)}
${cell("quiet",[1,1],`<div class="noo-cellhead"><p class="noo-label">before</p><p class="noo-bento__title noo-cellhead__title"><span class="noo-dot" data-hue="blue"></span>Dataflix</p></div>`)}
${cell("quiet",[1,1],`<div class="noo-cellhead"><p class="noo-label">one year</p><p class="noo-bento__title noo-cellhead__title"><span class="noo-dot" data-hue="lavender"></span>Hashnode</p></div>`)}
${cell("quiet",[1,1],`<div class="noo-cellhead"><p class="noo-label">two years</p><p class="noo-bento__title noo-cellhead__title"><span class="noo-dot" data-hue="pink"></span>Terrible Tiny Tales</p></div>`)}
${cell("glass",[2,1],`<p class="noo-label" style="margin:0">the through-line</p><div class="noo-bento__chips">${chip("editors","peach")}${chip("design systems","lavender")}${chip("agent systems","blue")}${chip("full-stack","green")}</div>`)}
${cell("quiet",[2,1],`<p class="noo-label" style="margin:0">résumé</p><p class="noo-bento__text">One page, as a download, when it exists.</p>`)}
</div>`;

const catEntry = () => `<article class="noo-cat__entry" style="margin-top:0;width:760px"><div class="noo-stack noo-stack--g8"><div class="noo-row noo-row--g8 noo-row--baseline"><h4 class="noo-heading noo-h4">Chip</h4><span class="noo-label" style="color:var(--muted)">stable</span></div><p class="noo-text noo-body-sm noo-text--muted">A pill in one of the seven hues.</p><p class="noo-label" style="color:var(--muted)">slot</p><div class="noo-cat__api"><p><b>hue</b><i>*</i> hue | accent</p><p><b>label</b> text ≤ 24</p><p><b>dot</b> boolean · default true</p></div></div><div class="noo-cat__demo">${chip("editor","lavender")}</div></article>`;

const canvasSchematic = () => `<svg viewBox="0 0 760 340" width="760" height="340" style="display:block;border:1px solid var(--rule);border-radius:var(--r-md);background:var(--ground)"><defs><pattern id="cg" width="40" height="40" patternUnits="userSpaceOnUse"><path style="stroke:var(--grid-line)" d="M40 0H0V40" fill="none"/></pattern></defs><rect width="760" height="340" fill="url(#cg)"/><g> style="fill:var(--surface);stroke:var(--rule)"<rect x="150" y="60" width="120" height="90" rx="10"/><rect x="490" y="60" width="120" height="90" rx="10"/><rect x="60" y="150" width="120" height="90" rx="10"/><rect x="580" y="150" width="120" height="90" rx="10"/><rect x="150" y="240" width="120" height="90" rx="10" /><rect x="490" y="240" width="120" height="90" rx="10"/><rect x="300" y="150" width="160" height="110" rx="10"/></g><rect style="fill:var(--blue)" x="150" y="60" width="52" height="42" rx="8"/><rect style="fill:var(--peach)" x="490" y="60" width="52" height="42" rx="8"/><rect style="fill:var(--yellow)" x="60" y="150" width="52" height="42" rx="8"/><rect style="fill:var(--lavender)" x="580" y="150" width="52" height="42" rx="8"/><rect style="fill:var(--pink)" x="150" y="240" width="52" height="42" rx="8"/><rect style="fill:var(--green)" x="490" y="240" width="52" height="42" rx="8"/><g transform="translate(362 112)"><rect width="36" height="24" rx="12" fill="#fff" fill-opacity=".6" stroke="#fff" stroke-opacity=".9"/><circle style="fill:var(--eye)" cx="11" cy="12" r="3.6"/><circle style="fill:var(--eye)" cx="25" cy="12" r="3.6"/></g><rect style="fill:var(--surface);stroke:var(--rule)" x="24" y="200" width="80" height="120" rx="12" fill-opacity=".8"/><rect style="fill:var(--surface);stroke:var(--rule)" x="240" y="296" width="280" height="30" rx="15" fill-opacity=".8"/><text style="font-family:var(--ff-display);fill:var(--ink)" x="660" y="322" font-size="14">N●RIGINS</text><text style="font-family:var(--ff-mono);fill:var(--muted)" x="34" y="222" font-size="8">MENU</text><text style="font-family:var(--ff-mono);fill:var(--muted)" x="700" y="30" font-size="8">THEME</text></svg>`;

export const items = [
  item({ name: "NavBar", layer: "organism · page mode", desc: "glass-2, 60 tall, sticky. Wordmark left, links right, the current one accent-deep with a 2px underline; a trailing slot; a skip link first. Below 900 the links become a bottom glass sheet.", reads: "glass-2 · --accent-deep · --ink-2 · Wordmark", verdict: "Fix",
    note: "Right in shape. Link 15/500 → <code>ui</code>; link height 40 → <code>--ctl-md</code> 44, which is also the hit target the spec asks for; bar height → <code>--bar</code>.",
    demo: navbar(), wide: true, tight: true }),
  item({ name: "Rail → Menu", layer: "organism · merged 2026-09-14 (D9)", desc: "248 wide, glass-2, sticky and viewport-tall. Groups carry a hue — the three layers — with a mono eyebrow and a dot; one level of nesting, shown only under the current branch; the current mark is a 2px bar on the leading edge; trailing slot pinned to the bottom.", reads: "glass-2 · --{hue}-deep · --ink-2 · --muted · --r-md", verdict: "Merge",
    note: "Your note made this a merge: the Rail is one of three hand-built menus (with the canvas switcher and the NavBar sheet). It becomes <code>Menu</code>’s column form — see the Menu board — keeping the groups and their hues, the one level of nesting and the skip link, and taking the ink-pill current marker from your reference. Decision D9. <b>Done:</b> <code>Menu</code> ships in five forms — column, rail, two columns, floating, sheet — and <code>Rail</code> is a deprecated alias for its column. The sample is the Menu; the current item is the ink pill.",
    demo: `<div class="rv-row rv-row--start" style="gap:32px">${rail(600)}<div class="rv-col" style="max-width:36ch;gap:12px"><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">The current mark is the bar’s underline rotated onto the edge a column has. Sub-items open only under the branch you are in.</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">Below 900 it becomes a strip across the top that scrolls sideways, groups intact.</p></div></div>` }),
  item({ name: "Menu", layer: "organism · missing", desc: "One menu for the platform: column, icon rail, two columns, floating on the canvas, bottom sheet on a phone. Items with an icon, a label, a badge or an add action, one level of children on a rule; the current item is an ink pill. Drawn from your reference on its own board.", reads: "glass-2 · --r-xl · --ink · --ground · --surface · --rule · Icon · Label", verdict: "Missing",
    note: "Replaces Rail, the canvas’s hardcoded <code>menu</code> panel and the NavBar’s sheet. Placeable on a canvas as a <code>menu</code> node with its items edited in the inspector. Decision D9.",
    demo: `<div class="rv-row" style="gap:16px;align-items:center"><span class="rv-cap">see the Menu board →</span></div>` }),
  item({ name: "Footer", layer: "organism · page mode", desc: "On the ground, a hairline above. The name in running text, a mono line of meta, links, a trailing slot for the theme switch.", reads: "--rule · --ink-2 · --muted · Wordmark text", verdict: "Fix",
    note: "14.5 and 13 → <code>body-sm</code> and <code>caption</code> tokens. Otherwise finished.",
    demo: footer(), wide: true, tight: true }),
  item({ name: "BlockCard · RoadmapItem", layer: "organism · the Work item and the not-yet item", desc: "Card + a hue dot + eyebrow + h4 + one line + details + chips, the whole card a link with <code>href</code>. RoadmapItem is the same card with a description and a progress label, for a block that is not here yet.", reads: "Card · Chip · Dot · --{hue}-deep", verdict: "Merge",
    note: "RoadmapItem shares BlockCard’s CSS selectors already and Roadmap left the portfolio. Retire it: <code>BlockCard</code> with <code>state=\"sleep\"</code> and a <code>progress</code> prop is the same object. The 10px hue mark becomes the 12px <code>Dot</code>.",
    demo: `<div class="rv-row rv-row--start" style="gap:20px">${blockCard()}${roadmapItem()}</div>` }),
  item({ name: "MediaCard", layer: "organism · picture beside words", desc: "A picture region beside the words, or above them; the region falls back to the hue’s wash under the grain. Eyebrow, title, line, footer slot; a link with <code>href</code>.", reads: "--surface · --r-xl · --e1/--e3 · --{hue} · grain", verdict: "Fix",
    note: "The docstring still says “no photographs anywhere on the platform” — reversed 2026-09-11 when <code>Image</code> landed. Update it, and let <code>media</code> take an Image explicitly. Reads the hue slot.",
    demo: mediaCard() }),
  item({ name: "Quote", layer: "organism · attributed words", desc: "A figure, a blockquote and a figcaption. Optional figure above (a measured number), optional media beside. The attribution is a left rule, not a glyph.", reads: "--surface · --r-xl · --e2 · --accent-deep", verdict: "Fix",
    note: "It is a <code>Card</code> at padding 40 and radius xl written out again in its own rules. Stand it on Card (<code>padding=\"lg\"</code>, <code>radius=\"xl\"</code>) and the material stays in one place.",
    demo: quote() }),
  item({ name: "ProfileCard", layer: "organism · large-format media", desc: "The picture is the whole card and its bottom turns to frosted glass — a blurred copy under a mask, no edge anywhere — with the words standing on it. Hairline, lit top edge, 118° sweep, grain; a bloom of the picture beneath. Proportional 15% corner.", reads: "--glass-* · --shade · --e3 · grain · --{hue}", verdict: "Keep",
    note: "The one component that carries all four material cues at once; it is the reference for what glass means here. Corrected three times in a day and the reasons are written down. Reads the hue slot.",
    demo: `<div class="rv-row rv-row--start" style="gap:32px">${profile(300,"peach")}${profile(220,"lavender")}</div>` }),
  item({ name: "Deck · Carousel", layer: "organism · tracks that snap", desc: "Both are scroll containers with CSS scroll-snap — trackpad, swipe, arrow keys and a screen reader’s own scrolling work before hydration. Carousel peeks the neighbours; Deck publishes each card’s distance from centre and lets CSS do the depth.", reads: "--d-base · --ease · Dots", verdict: "Keep",
    note: "Keep both; they answer different questions (a row you step through, a stack with one forward). Share <code>Dots</code> rather than Deck borrowing Carousel’s class.",
    demo: `<div class="rv-col" style="gap:32px">${deck()}${carousel()}</div>` }),
  item({ name: "Bento · BentoCell", layer: "organism · the widget", desc: "The one grid at two sizes. As a widget: 4 × 3 cells of 144 with 16 gutters — 640 × 480, snapping into four boxes by three. As a page: ten fluid columns, rows that grow. Every cell does one job; one cell per widget is loud.", reads: "--grid-box · --grid-pad · --{hue} · --{hue}-ink · grain · --r-lg", verdict: "Fix",
    note: "The grid derives from the ground tokens by construction — the best-connected component in the package. Two fixes: <code>--bento-hue-ink</code> defaults to <code>--peach-ink</code> (should be <code>--accent-ink</code>), and the widget’s type sizes (96 · 48 · 22 · 20) are literals that should be the four widget type tokens. The chip restyle moves onto Chip.",
    demo: `<div class="rv-row rv-row--start" style="gap:32px">${bento()}<div class="rv-col" style="max-width:26ch;gap:12px"><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">The Work widget as it stands on the ring: one loud cell with the figure and a field drawing, four quiet cells, one glass cell.</p><p class="noo-body-sm" style="margin:0;color:var(--ink-2)"><code>probe12</code> fails the sweep on anything but exactly one loud cell.</p></div></div>`, wide: true }),
  item({ name: "Catalogue", layer: "organism · the registry, rendered", desc: "Every registry entry: name, status, kind, the prop schema as readable lines, and a live example. One rendering for the showcase and the admin, so the two cannot drift.", reads: "Heading · Text · Label · --rule · --surface", verdict: "Fix",
    note: "Keep it in the package. Fix the demo well: it is <code>--surface</code>, so every glass sample inside it is a grey box — the showcase screenshot shows exactly that. The well should be the ground, as on these boards. Group by <em>layer</em> (atoms · molecules · organisms) rather than by the registry’s seven groups, so the catalogue and this architecture agree.",
    demo: catEntry() }),
  item({ name: "SectionWidget · RegionLabel", layer: "organism · retired, still exported", desc: "SectionWidget enforced the widget rules as props and was retired for total freedom (probe12 took over). RegionLabel is the map label the portfolio stopped using in step 12.", reads: "Bento · Illustration", verdict: "Retire",
    note: "Remove SectionWidget’s export — nothing may keep a retired rule alive by accident. Mark RegionLabel <code>deprecated</code> in the registry until the editor gives regions a job again; the fixture can keep rendering it.",
    demo: `<div class="rv-row" style="gap:32px;align-items:flex-end"><div class="noo-region" style="width:360px;height:120px"><span class="noo-region__label" style="font-size:64px">Work</span><span class="noo-region__rule"></span></div><p class="rv-cap" style="max-width:30ch">RegionLabel: a display word at 96 canvas units over a dotted rule, decorative by design</p></div>` }),
  item({ name: "The canvas nodes", layer: "organism · @no-origins/ui/canvas", desc: "<code>CanvasShell</code> on React Flow, with four node types — blob, panel, widget, region — plus the minimap dressed as glass-1, the dotted threads, the view switcher and the chat panel. The base layout of every block.", reads: "everything above · --grid-box · --rule", verdict: "Keep",
    note: "Reviewed from source only; nothing here renders without React Flow. The structure is right and the hard-won constraints are documented in code. One naming fix: <code>Canvas</code>-layer CSS is 150 lines in components.css — it belongs in its own file, imported only by the canvas entry.",
    demo: `<div class="rv-row rv-row--start" style="gap:32px">${canvasSchematic()}<div class="rv-col" style="max-width:26ch;gap:10px"><p class="noo-body-sm" style="margin:0;color:var(--ink-2)">Six widgets on a box-quantised ring, Me at the centre, the one glass blob on the origin crosshair. Menu bottom-left, chat bottom-centre, wordmark bottom-right, theme top-right.</p></div></div>`, wide: true }),
];

export const title = "Organisms";
export const block = "portfolio";
export const body = `
${head({ eyebrow: "release review · layer 4 of 6", title: "Organisms", lead: "Molecules and atoms assembled into a distinct section of an interface. Fourteen exist. The material is right — ProfileCard is the clearest statement of it — and the fixes are about standing on the atoms below rather than restating them: a Quote is a Card, a Deck’s dots are the Carousel’s, a hue is read from the slot." })}
${legend()}
${items.join("")}
`;
