import { head, legend, group, item, chip, wordmark } from "../lib.mjs";
import { rail, themeSwitch } from "./organisms.mjs";

const wire = (label, style, cls = "") => `<div class="rv-wire ${cls}" style="${style}">${label}</div>`;

const pageWire = () => `<div style="width:520px;display:flex;flex-direction:column;gap:6px">${wire("NavBar · glass-2 · sticky · 60","height:44px","rv-wire--accent")}<div style="display:flex;justify-content:center;padding:12px 0;border:1px dashed var(--rule);border-radius:var(--r-md)"><div style="width:380px;display:flex;flex-direction:column;gap:6px">${wire("Container · max 1120 · gutters 24 / 48","height:32px")}${wire("Section · rhythm 96 / 64 · rise-in","height:120px")}${wire("Section","height:80px")}</div></div>${wire("Footer · hairline above · on the ground","height:44px")}</div>`;

const adminAsBuilt = () => `<div class="noo-page noo-page--railed" style="min-height:0;width:1344px;border:1px solid var(--rule);border-radius:var(--r-md);overflow:hidden">${rail(720)}<div class="noo-page__column" style="min-height:0"><main class="noo-page__main"><section class="noo-section noo-container" style="padding-block:48px">
<header class="noo-section-header"><p class="noo-label noo-section-header__label">no origins · admin</p><h1 class="noo-h1 noo-section-header__title">Three layers, in the order they depend on each other</h1><p class="noo-lead noo-section-header__lead">Projects are the pages. Systems are the mechanisms they are built with. Products plug into systems.</p></header>
<div style="display:grid;gap:24px;grid-template-columns:repeat(3,minmax(0,1fr))">${[["Live","0","Documents with a published version."],["Drafted","0","Saved in the editor, never published."],["Projects","1","4 systems, 0 products."]].map(([l,n,t]) => `<div class="noo-card"><div class="noo-stack noo-stack--g8"><p class="noo-label" style="margin:0;color:var(--muted)">${l}</p><h2 class="noo-heading noo-h2">${n}</h2><p class="noo-text noo-body-sm noo-text--muted">${t}</p></div></div>`).join("")}</div>
<div style="display:grid;gap:24px;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:48px">${[["Layer 1","Projects","peach","canvas","versions"],["Layer 2","Systems","lavender","read-only","R3"]].map(([e,t,h,c1,c2]) => `<a href="#" class="noo-card noo-card--interactive"><div class="noo-stack noo-stack--g8"><p class="noo-label" style="margin:0;color:var(--muted)">${e}</p><h3 class="noo-heading noo-h3">${t}</h3><p class="noo-text noo-body noo-text--muted">The pages, their drafts and their versions.</p><div class="noo-row noo-row--g8" style="margin-top:8px">${chip(c1,h)}${chip(c2,h)}</div></div></a>`).join("")}</div>
</section></main></div></div>`;

const toolWire = () => `<div style="width:1344px;height:720px;display:grid;grid-template-columns:248px minmax(0,1fr) 320px;grid-template-rows:56px minmax(0,1fr) 44px;gap:6px;border:1px solid var(--rule);border-radius:var(--r-md);padding:6px;box-sizing:border-box">
${wire("Rail · 248 · glass-2<br><br>groups = the three layers<br>current = 2px on the edge<br><br>trailing: theme · who is signed in","grid-row:1 / span 3;align-content:start;padding-top:24px","rv-wire--accent")}
${wire("Header · 56 · on the ground, hairline below · eyebrow SYSTEM · title · actions right (Preview · Publish)","grid-column:2 / span 2")}
<div class="rv-wire" style="display:flex;flex-direction:column;gap:8px;align-items:stretch;justify-content:flex-start;padding:20px">
  <div style="display:flex;justify-content:space-between;align-items:center"><span>Tabs · Tokens | Components | Contrast</span><span>Segmented · Light | Dark</span></div>
  <div style="flex:1;display:grid;grid-template-rows:repeat(7,1fr);gap:6px;margin-top:8px">${["Table header · mono label","row · 44 · hover ink 4%","row","row","row","row","row"].map((r,i) => `<div style="border:1px ${i===0?"solid":"dashed"} var(--rule);border-radius:6px;display:grid;place-items:center">${r}</div>`).join("")}</div>
  <span>main · fluid · gutters 32 · no 1120 cap · density from Table, not Cards</span>
</div>
${wire("Inspector · 320 · glass-1<br><br>the selected thing’s props, generated from its schema<br><br>Field · Select · Toggle · hue swatches","align-content:start;padding-top:24px")}
${wire("Footer bar · 44 · zoom · theme · block accent · desktop / phone · grid on / off — only under the editor","grid-column:2 / span 2")}
</div>`;

const tcell = (t, cls = "") => `<td class="noo-table__td ${cls}">${t}</td>`;
const toolBuilt = () => `<div class="noo-tool" style="min-height:0;width:1344px;height:640px;border:1px solid var(--rule);border-radius:var(--r-md);overflow:hidden">${rail(616)}<div class="noo-tool__column" style="min-height:0"><div class="noo-tool__screen noo-tool__screen--inspector noo-tool__screen--bar" style="height:640px">
<header class="noo-tool__header" style="position:static"><div class="noo-tool__heading"><p class="noo-label noo-tool__eyebrow">Projects</p><h1 class="noo-heading noo-h4 noo-tool__title">Portfolio</h1><div class="noo-tool__meta">${chip("live","green")}${chip("bhargav.no-origins.com","peach")}<span class="noo-text noo-body-sm noo-text--muted">saved 2 minutes ago</span></div></div><div class="noo-tool__actions"><button type="button" class="noo-btn noo-btn--secondary noo-btn--sm noo-glass noo-glass--1"><span class="noo-btn__text">Preview</span></button><button type="button" class="noo-btn noo-btn--primary noo-btn--sm"><span class="noo-btn__text">Publish</span></button></div></header>
<main class="noo-tool__main"><div class="noo-tabs"><div role="tablist" class="noo-tabs__list"><button type="button" role="tab" class="noo-tabs__tab" aria-selected="false">Documents</button><button type="button" role="tab" class="noo-tabs__tab" aria-selected="true">Versions</button><button type="button" role="tab" class="noo-tabs__tab" aria-selected="false">Settings</button></div><div role="tabpanel" class="noo-tabs__panel">
<div class="noo-table-wrap"><table class="noo-table"><thead><tr><th class="noo-label noo-table__th noo-table__cell--num" style="width:88px">Version</th><th class="noo-label noo-table__th">Label</th><th class="noo-label noo-table__th">By</th><th class="noo-label noo-table__th noo-table__cell--num">Published</th><th class="noo-label noo-table__th">State</th></tr></thead><tbody>
${[["12","Roadmap, honest counts","2026-09-14","live","green"],["11","Work ring at 2200","2026-09-11","superseded","grey"],["10","First publish","2026-09-08","superseded","grey"]].map(([v,l,d,st,h]) => `<tr>${tcell(v,"noo-table__cell--num")}${tcell(l)}${tcell("bhargav")}${tcell(d,"noo-table__cell--num")}${tcell(chip(st,h))}</tr>`).join("")}
</tbody></table></div></div></div>
<header class="noo-section-header noo-section-header--flush"><h3 class="noo-heading noo-h3 noo-section-header__title">The read-back</h3><p class="noo-text noo-lead noo-section-header__lead">Publishing ends at a read-back, not at the webhook.</p></header></main>
<aside class="noo-glass noo-glass--1 noo-tool__inspector" style="position:static;max-height:none"><header class="noo-section-header noo-section-header--flush"><p class="noo-label noo-section-header__label">selected</p><h4 class="noo-heading noo-h4 noo-section-header__title">BlockCard</h4></header><div class="noo-field"><label class="noo-field__label">Title</label><div class="noo-glass noo-glass--1 noo-field__box"><input class="noo-field__input" value="Neptune, Hashnode’s editor"></div></div><div class="noo-field noo-field--select"><label class="noo-field__label">Hue</label><div class="noo-glass noo-glass--1 noo-field__box"><select class="noo-field__input noo-field__select"><option>blue</option></select><span class="noo-field__adorn"><svg class="noo-field__chevron" viewBox="0 0 16 16" aria-hidden="true"><path d="M4 6l4 4 4-4" style="fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round"/></svg></span></div></div><div class="noo-glass noo-glass--1 noo-segmented" role="group" aria-label="State"><button type="button" class="noo-segmented__btn" aria-pressed="true">Idle</button><button type="button" class="noo-segmented__btn">Asleep</button></div></aside>
<footer class="noo-glass noo-glass--2 noo-tool__bar" style="position:static"><div class="noo-glass noo-glass--1 noo-segmented" role="group" aria-label="Viewport"><button type="button" class="noo-segmented__btn" aria-pressed="true">Desktop</button><button type="button" class="noo-segmented__btn">Phone</button></div><span class="noo-text noo-body-sm noo-text--muted">zoom 0.9</span>${themeSwitch()}</footer>
</div></div></div>`;

const prose = () => `<article class="noo-document"><h2>What a document wears</h2><p>The editor block publishes documents. A document is <strong>markdown plus one directive</strong> — a link that moves the viewport — and it renders in a 68ch column.</p><h3>Lists and code</h3><ul><li>Lists take a marker in <code>--muted</code>, so the text leads.</li><li>Inline code sits on <code>--ground-2</code> at the chips’ radius.</li></ul><pre><code>const blocks = 7;</code></pre><blockquote>A blockquote stands on the accent rule at the lead size.</blockquote><table><thead><tr><th>Layer</th><th>Count</th></tr></thead><tbody><tr><td>Atoms</td><td>15</td></tr><tr><td>Molecules</td><td>14</td></tr></tbody></table></article>`;

export const items = [
  item({ name: "Page", layer: "template · page mode", desc: "A flex column: nav slot, <code>main#main</code>, footer slot, filling the viewport. <code>Container</code> is the 1120 measure with 24 / 48 gutters; <code>Section</code> adds the 96 / 64 rhythm and the page’s one arrival.", reads: "NavBar · Footer · Section · Container", verdict: "Keep",
    note: "Right for what it is: a reading layout for documents and the showcase. It is not a tool layout, and that is the admin’s problem below.",
    demo: pageWire() }),
  item({ name: "Page with a rail — the admin as it was", layer: "template · the layout you flagged · replaced 2026-09-14", desc: "The current admin: <code>Page</code> with a <code>rail</code>, and every screen is one <code>Section</code> — a 1120 container with 48px gutters — holding a SectionHeader, a grid of stat cards, and cards of muted paragraphs with chips. Reconstructed here from the source, at real size.", reads: "Rail · Section · Card · Heading · Chip", verdict: "Fix",
    note: "Five things are wrong, and none of them is the Rail. (1) A reading column beside a tool rail — the content is centred in 1120 with a marketing page’s gutters, so the screen is a landing page with a sidebar. (2) Stat cards with a Bowlby number are the “generic dashboard pattern” Brand.md §10 rules out, and a Bowlby <code>h2</code> for a count is a heading that is not a heading. (3) No header: Admin.md §3 asks for rail + header + inspector; the title floats in the column. (4) Spacing is Tailwind utilities in app files (<code>mt-12</code>, <code>mb-10</code>, <code>grid md:grid-cols-3</code>) — layout no component holds, the exact drift Scene-Schema found. (5) The eyebrow says <em>Project</em>, the rail says <em>Projects</em>, and the accent is yellow where Admin.md says lavender. <b>Replaced:</b> every screen is a <code>ToolScreen</code> now; <code>Page</code>’s <code>rail</code> prop is deprecated.",
    demo: adminAsBuilt(), wide: true, tight: true }),
  item({ name: "Tool", layer: "template · built 2026-09-14 (D6, option B)", desc: "A control surface: rail · header · main · inspector · footer bar. Main is fluid with 32px gutters and gets its density from a <code>Table</code>, not from cards. The header carries the layer eyebrow, the title and the screen’s actions. The inspector and footer bar appear only where a screen has a selection or a viewport.", reads: "Rail · Tabs · Table · Segmented · Field · Button", verdict: "Missing",
    note: "This is the template the admin should wear and the package does not have. Three options are on the table — see the note beside this board. My recommendation is <strong>B</strong>: build <code>Tool</code> as a real template with the five regions, and let <code>Page</code> stay a reading layout. It costs Table, Tabs and Segmented first, which the admin needs anyway. <b>Built:</b> <code>Tool</code> + <code>ToolScreen</code>; the admin’s nine screens wear it with zero utility classes. Below the wireframe, the shell as built, in the real classes.",
    demo: `<div class="rv-col" style="gap:20px">${toolBuilt()}${toolWire()}<table class="rv-table" style="width:1344px"><tr><th>option</th><th>what it is</th><th>cost</th><th>why not / why</th></tr>
<tr><td>A · Patch Page</td><td>Keep Page + rail; add a header slot; drop the 1120 cap when railed</td><td>a day</td><td>Cheapest. Leaves stat cards and utility spacing in place — the two things that make it read generic</td></tr>
<tr><td>B · Tool template (recommended)</td><td>A fifth region set — rail · header · main · inspector · bar — as its own template, with Table, Tabs, Segmented built first</td><td>a week, in the package</td><td>Page stays honest as a reading layout; the admin gets a tool’s chrome; the editor’s inspector has a home before the editor exists</td></tr>
<tr><td>C · Canvas-first admin</td><td>The admin is itself a CanvasShell</td><td>—</td><td>Already rejected in Admin.md §3: a control surface whose controls pan away is a demo, not a tool</td></tr></table></div>`, wide: true, tight: true }),
  item({ name: "Canvas", layer: "template · canvas mode", desc: "<code>CanvasShell</code>: the infinite ground, nodes hand-placed in boxes, chat bottom-centre, menu bottom-left, wordmark bottom-right, theme and reset top-right. Below 900 it becomes a tall page the browser scrolls; without JavaScript a single no-script style block linearises it.", reads: "everything", verdict: "Keep",
    note: "The base layout of every block, decided and built. One change from your note: the bottom-left <code>menu</code> panel leaves the template and becomes a placed <code>Menu</code> node (Menu board), so a scene decides whether it has one and what it lists.",
    demo: `<div class="rv-row" style="gap:20px">${wire("CanvasShell · 100dvh · the ground","width:520px;height:220px;position:relative","")}</div>`.replace('</div></div>', `<div style="position:absolute;left:12px;bottom:12px" class="rv-wire rv-wire--accent" style="text-decoration:line-through">menu → a placed node</div><div style="position:absolute;left:50%;bottom:12px;transform:translateX(-50%);width:200px" class="rv-wire rv-wire--accent">chat</div><div style="position:absolute;right:12px;bottom:12px" class="rv-wire">N●RIGINS</div><div style="position:absolute;right:12px;top:12px" class="rv-wire">theme · reset</div><div style="position:absolute;left:12px;top:12px" class="rv-wire">minimap</div></div></div>`) }),
  item({ name: "Document", layer: "template · built 2026-09-14", desc: "The 68ch reading column the editor block will publish into. Today <code>.noo-prose</code> sets a width and nothing else.", reads: "type scale · --rule · --ground-2", verdict: "Missing",
    note: "Markdown rendered into the ramp: h2–h4, lists with a marker in <code>--muted</code>, code on <code>--ground-2</code>, a blockquote rule, a table. R4 fixed the prose shape; this is what it wears. Needed before step 6 (the document renderer). <b>Built:</b> <code>Document</code> — <code>.noo-document</code>, with <code>.noo-prose</code> as the alias; this sample is the real stylesheet.",
    demo: prose() }),
];

export const title = "Templates";
export const block = "tools";
export const body = `
${head({ eyebrow: "release review · layer 5 of 6", title: "Templates", lead: "The shells a screen is poured into. Two are built and one of them is being worn by the wrong kind of screen: the admin is a tool in a reading layout. The fix is a template, not a restyle — and the missing one, Document, is what the editor block will need first." })}
${legend()}
${items.join("")}
`;
